# plugin manager
[[plugins]]
repo = 'shougo/dein.vim'

# Completion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

# Colorscheme
[[plugins]]
repo = 'sickill/vim-monokai'

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
